on: push
jobs:
  buil-node:
    runs-on: ubuntu-lates
    container: node. 16
    steps: 
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3 
      - run: npm install
      - run: npm run test:NOT-HEADLESS features/**/*.feature